// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: NFDefine.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NFMsg {

  /// <summary>Holder for reflection information generated from NFDefine.proto</summary>
  public static partial class NFDefineReflection {

    #region Descriptor
    /// <summary>File descriptor for NFDefine.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static NFDefineReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5ORkRlZmluZS5wcm90bxIFTkZNc2cqmAoKDkVHYW1lRXZlbnRDb2RlEhAK",
            "DEVHRUNfU1VDQ0VTUxAAEhUKEUVHRUNfVU5LT1dOX0VSUk9SEAESFgoSRUdF",
            "Q19BQ0NPVU5UX0VYSVNUEAISGwoXRUdFQ19BQ0NPVU5UUFdEX0lOVkFMSUQQ",
            "AxIWChJFR0VDX0FDQ09VTlRfVVNJTkcQBBIXChNFR0VDX0FDQ09VTlRfTE9D",
            "S0VEEAUSGAoURUdFQ19BQ0NPVU5UX1NVQ0NFU1MQBhIbChdFR0VDX1ZFUklG",
            "WV9LRVlfU1VDQ0VTUxAHEhgKFEVHRUNfVkVSSUZZX0tFWV9GQUlMEAgSHQoZ",
            "RUdFQ19TRUxFQ1RTRVJWRVJfU1VDQ0VTUxAJEhoKFkVHRUNfU0VMRUNUU0VS",
            "VkVSX0ZBSUwQChIYChRFR0VDX0NIQVJBQ1RFUl9FWElTVBBuEhoKFkVHRUNf",
            "U1ZSWk9ORUlEX0lOVkFMSUQQbxIZChVFR0VDX0NIQVJBQ1RFUl9OVU1PVVQQ",
            "cBIaChZFR0VDX0NIQVJBQ1RFUl9JTlZBTElEEHESGwoXRUdFQ19DSEFSQUNU",
            "RVJfTk9URVhJU1QQchIYChRFR0VDX0NIQVJBQ1RFUl9VU0lORxBzEhkKFUVH",
            "RUNfQ0hBUkFDVEVSX0xPQ0tFRBB0EhYKEkVHRUNfWk9ORV9PVkVSTE9BRBB1",
            "EhMKD0VHRUNfTk9UX09OTElORRB2EhcKE0VHRUNfQUxSRUFZX0lOX1RFQU0Q",
            "dxIcChhFR0VDX0lOVkFMSURfVEVBTV9JTlZJVEUQeBISCg5FR0VDX1RFQU1f",
            "RlVMTBB5EhoKFkVHRUNfTUFJTF9VUERBVEVfRVJST1IQehIcChhFR0VDX01B",
            "SUxfVE9OQU1FX0lOVkFMSUQQexIaChZFR0VDX01BSUxfREVMRVRFX0VSUk9S",
            "EHwSGwoXRUdFQ19NQUlMX1RPV05BTUVfRVFVQUwQfRITCg9FR0VDX0xBQ0tf",
            "TU9ORVkQfhIVChFFR0VDX0ZVTExfUEFDS0FHRRB/EhYKEUVHRUNfSU5WQUxJ",
            "RF9JVEVNEIABEh0KGEVHRUNfSU5WQUxJRF9DT05TSUdOTUVOVBCBARIYChNF",
            "R0VDX05PVF9FTk9VR0hfVklQEIIBEhQKD0VHRUNfTkVFRF9MRVZFTBCDARIZ",
            "ChRFR0VDX01BWF9GUklFTkRfTElTVBCEARIYChNFR0VDX01BWF9FTkVNWV9M",
            "SVNUEIUBEhgKE0VHRUNfTUFYX0dBTkdTX0xTSVQQhgESGgoVRUdFQ19MSU1J",
            "VFNfVE9fUklHSFRTEIcBEhwKF0VHRUNfSU5WQUxJRF9HQU5HU19OQU1FEIgB",
            "EhwKF0VHRUNfUkVQRUFUX0VOVEVSX0dBTkdTEIkBEh0KGEVHRUNfSU5WQUxJ",
            "RF9HQU5HU01FTUJFUhCKARIcChdFR0VDX01BU1RFUl9MRUFWRV9HQU5HUxCL",
            "ARIbChZFR0VDX0dBTkdTX1RJVExFX09VVE9GEIwBEh0KGEVHRUNfRU5URVJf",
            "R0FURVdBWV9GQUlMRBCNARIYChNFR0VDX05PX1NFUlZFUjRaT05FEI4BEhcK",
            "EkVHRUNfSU5WQUxJRF9TS0lMTBCPARIeChlFR0VDX0NSRUFURV9HVUlMRF9T",
            "VUNDRVNTEMgBEhwKF0VHRUNfSk9JTl9HVUlMRF9TVUNDRVNTEMkBEh0KGEVH",
            "RUNfTEVBVkVfR1VJTERfU1VDQ0VTUxDKASocCglFU3luTXNnSUQSDwoLRVNN",
            "SV9VTktOT1cQACqOMQoKRUdhbWVNc2dJRBIPCgtFR01JX1VOS05PVxAAEhUK",
            "EUVHTUlfRVZFTlRfUkVTVUxUEAESGAoURUdNSV9FVkVOVF9UUkFOU1BPTkQQ",
            "AhIVChFFR01JX0NMT1NFX1NPQ0tFVBADEh0KGUVHTUlfV1RNX1dPUkxEX1JF",
            "R0lTVEVSRUQQChIfChtFR01JX1dUTV9XT1JMRF9VTlJFR0lTVEVSRUQQCxIa",
            "ChZFR01JX1dUTV9XT1JMRF9SRUZSRVNIEAwSHQoZRUdNSV9MVE1fTE9HSU5f",
            "UkVHSVNURVJFRBAUEh8KG0VHTUlfTFRNX0xPR0lOX1VOUkVHSVNURVJFRBAV",
            "EhoKFkVHTUlfTFRNX0xPR0lOX1JFRlJFU0gQFhIeChpFR01JX1BUV0dfUFJP",
            "WFlfUkVHSVNURVJFRBAeEiAKHEVHTUlfUFRXR19QUk9YWV9VTlJFR0lTVEVS",
            "RUQQHxIbChdFR01JX1BUV0dfUFJPWFlfUkVGUkVTSBAgEhwKGEVHTUlfR1RX",
            "X0dBTUVfUkVHSVNURVJFRBAoEh4KGkVHTUlfR1RXX0dBTUVfVU5SRUdJU1RF",
            "UkVEECkSGQoVRUdNSV9HVFdfR0FNRV9SRUZSRVNIECoSGgoWRUdNSV9EVFdf",
            "REJfUkVHSVNURVJFRBA8EhwKGEVHTUlfRFRXX0RCX1VOUkVHSVNURVJFRBA9",
            "EhcKE0VHTUlfRFRXX0RCX1JFRlJFU0gQPhIVChFFR01JX1NUU19ORVRfSU5G",
            "TxBGEhoKFkVHTUlfU1RTX1NFUlZFUl9SRVBPUlQQWhIXChNFR01JX1NUU19I",
            "RUFSVF9CRUFUEGQSEgoORUdNSV9SRVFfTE9HSU4QZRISCg5FR01JX0FDS19M",
            "T0dJThBmEhMKD0VHTUlfUkVRX0xPR09VVBBnEhcKE0VHTUlfUkVRX1dPUkxE",
            "X0xJU1QQbhIXChNFR01JX0FDS19XT1JMRF9MSVNUEG8SGgoWRUdNSV9SRVFf",
            "Q09OTkVDVF9XT1JMRBBwEhoKFkVHTUlfQUNLX0NPTk5FQ1RfV09STEQQcRIg",
            "ChxFR01JX1JFUV9LSUNLX0NMSUVOVF9JTldPUkxEEHISGAoURUdNSV9SRVFf",
            "Q09OTkVDVF9LRVkQeBIYChRFR01JX0FDS19DT05ORUNUX0tFWRB6EhsKFkVH",
            "TUlfUkVRX1NFTEVDVF9TRVJWRVIQggESGwoWRUdNSV9BQ0tfU0VMRUNUX1NF",
            "UlZFUhCDARIXChJFR01JX1JFUV9ST0xFX0xJU1QQhAESFwoSRUdNSV9BQ0tf",
            "Uk9MRV9MSVNUEIUBEhkKFEVHTUlfUkVRX0NSRUFURV9ST0xFEIYBEhkKFEVH",
            "TUlfUkVRX0RFTEVURV9ST0xFEIcBEhoKFUVHTUlfUkVRX1JFQ09WRVJfUk9M",
            "RRCIARIcChdFR01JX1JFUV9MT0FEX1JPTEVfREFUQRCMARIcChdFR01JX0FD",
            "S19MT0FEX1JPTEVfREFUQRCNARIcChdFR01JX1JFUV9TQVZFX1JPTEVfREFU",
            "QRCOARIcChdFR01JX0FDS19TQVZFX1JPTEVfREFUQRCPARIbChZFR01JX1JF",
            "UV9MT0FEX09CSl9EQVRBEJABEhsKFkVHTUlfQUNLX0xPQURfT0JKX0RBVEEQ",
            "kQESGwoWRUdNSV9SRVFfU0FWRV9PQkpfREFUQRCSARIbChZFR01JX0FDS19T",
            "QVZFX09CSl9EQVRBEJMBEhgKE0VHTUlfUkVRX0VOVEVSX0dBTUUQlgESGAoT",
            "RUdNSV9BQ0tfRU5URVJfR0FNRRCXARIYChNFR01JX1JFUV9MRUFWRV9HQU1F",
            "EJgBEhgKE0VHTUlfQUNLX0xFQVZFX0dBTUUQmQESFwoSRUdNSV9SRVFfU1dB",
            "UF9HQU1FEJoBEhgKE0VHTUlfUkVRX1NXQVBfU0NFTkUQmwESGAoTRUdNSV9B",
            "Q0tfU1dBUF9TQ0VORRCcARIdChhFR01JX1JFUV9TV0FQX0hPTUVfU0NFTkUQ",
            "nQESHQoYRUdNSV9BQ0tfU1dBUF9IT01FX1NDRU5FEJ4BEh8KGkVHTUlfUkVR",
            "X0VOVEVSX0dBTUVfRklOSVNIEJ8BEh8KGkVHTUlfQUNLX0VOVEVSX0dBTUVf",
            "RklOSVNIEKABEhgKE0VHTUlfUkVRX0FDS19SRUxJVkUQtAESGgoVRUdNSV9B",
            "Q0tfT0JKRUNUX0VOVFJZEMgBEhoKFUVHTUlfQUNLX09CSkVDVF9MRUFWRRDJ",
            "ARIjCh5FR01JX0FDS19PQkpFQ1RfUFJPUEVSVFlfRU5UUlkQygESIQocRUdN",
            "SV9BQ0tfT0JKRUNUX1JFQ09SRF9FTlRSWRDLARIaChVFR01JX0FDS19QUk9Q",
            "RVJUWV9JTlQQ0gESHAoXRUdNSV9BQ0tfUFJPUEVSVFlfRkxPQVQQ0wESHQoY",
            "RUdNSV9BQ0tfUFJPUEVSVFlfU1RSSU5HENQBEh0KGEVHTUlfQUNLX1BST1BF",
            "UlRZX09CSkVDVBDWARIeChlFR01JX0FDS19QUk9QRVJUWV9WRUNUT1IyENcB",
            "Eh4KGUVHTUlfQUNLX1BST1BFUlRZX1ZFQ1RPUjMQ2AESFQoQRUdNSV9BQ0tf",
            "QUREX1JPVxDcARIYChNFR01JX0FDS19SRU1PVkVfUk9XEN0BEhYKEUVHTUlf",
            "QUNLX1NXQVBfUk9XEN4BEhgKE0VHTUlfQUNLX1JFQ09SRF9JTlQQ3wESGgoV",
            "RUdNSV9BQ0tfUkVDT1JEX0ZMT0FUEOABEhsKFkVHTUlfQUNLX1JFQ09SRF9T",
            "VFJJTkcQ4gESGwoWRUdNSV9BQ0tfUkVDT1JEX09CSkVDVBDjARIcChdFR01J",
            "X0FDS19SRUNPUkRfVkVDVE9SMhDkARIcChdFR01JX0FDS19SRUNPUkRfVkVD",
            "VE9SMxDlARIaChVFR01JX0FDS19SRUNPUkRfQ0xFQVIQ+gESGQoURUdNSV9B",
            "Q0tfUkVDT1JEX1NPUlQQ+wESGwoWRUdNSV9BQ0tfREFUQV9GSU5JU0hFRBCE",
            "AhIbChZFR01JX1JFUV9TVEFSVF9PUFBORU5UEMQJEhsKFkVHTUlfQUNLX1NU",
            "QVJUX09QUE5FTlQQxQkSGQoURUdNSV9SRVFfRU5EX09QUE5FTlQQxgkSGQoU",
            "RUdNSV9BQ0tfRU5EX09QUE5FTlQQxwkSHAoXRUdNSV9SRVFfU0VBUkNIX09Q",
            "UE5FTlQQyAkSHAoXRUdNSV9BQ0tfU0VBUkNIX09QUE5FTlQQyQkSGwoWRUdN",
            "SV9SRVFfQURKVVNUX0dBTUJMRRDKCRISCg1FR01JX1JFUV9NT1ZFEM4JEhIK",
            "DUVHTUlfQUNLX01PVkUQzwkSGQoURUdNSV9SRVFfTU9WRV9JTU1VTkUQ0AkS",
            "GQoURUdNSV9BQ0tfTU9WRV9JTU1VTkUQ0QkSGAoTRUdNSV9SRVFfU1RBVEVf",
            "U1lOQxDSCRIYChNFR01JX0FDS19TVEFURV9TWU5DENMJEhsKFkVHTUlfUkVR",
            "X1NLSUxMX09CSkVDVFgQ2AkSGwoWRUdNSV9BQ0tfU0tJTExfT0JKRUNUWBDZ",
            "CRIXChJFR01JX1JFUV9TS0lMTF9QT1MQ2gkSFwoSRUdNSV9BQ0tfU0tJTExf",
            "UE9TENsJEhkKFEVHTUlfUkVRX0lURU1fT0JKRUNUENwJEhkKFEVHTUlfQUNL",
            "X0lURU1fT0JKRUNUEN0JEhYKEUVHTUlfUkVRX0lURU1fUE9TEN4JEhYKEUVH",
            "TUlfQUNLX0lURU1fUE9TEN8JEhIKDUVHTUlfUkVRX0NIQVQQ4gkSEgoNRUdN",
            "SV9BQ0tfQ0hBVBDjCRIXChJFR01JX1JFUV9TQUxFX0lURU0Q5AkSGAoTRUdN",
            "SV9SRVFfU1BMSVRfSVRFTRDlCRIaChVFR01JX1JFUV9QUk9EVUNFX0lURU0Q",
            "5gkSFwoSRUdNSV9SRVFfUElDS19JVEVNEOcJEhkKFEVHTUlfUkVRX0FDQ0VQ",
            "VF9UQVNLEOgJEhwKF0VHTUlfUkVRX0NPTVBFTEVURV9UQVNLEOkJEhsKFkVH",
            "TUlfQUNLX09OTElORV9OT1RJRlkQigoSHAoXRUdNSV9BQ0tfT0ZGTElORV9O",
            "T1RJRlkQiwoSGgoVRUdNSV9SRVFfQ1JFQVRFX0dVSUxEEJQKEhoKFUVHTUlf",
            "QUNLX0NSRUFURV9HVUlMRBCVChIYChNFR01JX1JFUV9KT0lOX0dVSUxEEJYK",
            "EhgKE0VHTUlfQUNLX0pPSU5fR1VJTEQQlwoSGQoURUdNSV9SRVFfTEVBVkVf",
            "R1VJTEQQmAoSGQoURUdNSV9BQ0tfTEVBVkVfR1VJTEQQmQoSFwoSRUdNSV9S",
            "RVFfT1BSX0dVSUxEEJoKEhcKEkVHTUlfQUNLX09QUl9HVUlMRBCbChIaChVF",
            "R01JX1JFUV9TRUFSQ0hfR1VJTEQQnAoSGgoVRUdNSV9BQ0tfU0VBUkNIX0dV",
            "SUxEEJ0KEhsKFkVHTUlfUkVRX09QUl9HVUlMRElORk8QngoSGwoWRUdNSV9B",
            "Q0tfT1BSX0dVSUxESU5GTxCfChIdChhFR01JX1JFUV9HVUlMREVDVFlQRUlO",
            "Rk8QoAoSHQoYRUdNSV9BQ0tfR1VJTERFQ1RZUEVJTkZPEKEKEh0KGEVHTUlf",
            "U0VUX0dVSUxERUNUWVBFSU5GTxCiChIdChhFR01JX1JlcUVudGVyR3VpbGRF",
            "Y3R5cGUQowoSHgoZRUdFQ19SRVFfQ1JFQVRFX0NIQVRHUk9VUBD4ChIeChlF",
            "R0VDX0FDS19DUkVBVEVfQ0hBVEdST1VQEPkKEhwKF0VHRUNfUkVRX0pPSU5f",
            "Q0hBVEdST1VQEPoKEhwKF0VHRUNfQUNLX0pPSU5fQ0hBVEdST1VQEPsKEh0K",
            "GEVHRUNfUkVRX0xFQVZFX0NIQVRHUk9VUBD8ChIdChhFR0VDX0FDS19MRUFW",
            "RV9DSEFUR1JPVVAQ/QoSJAofRUdFQ19SRVFfU1VCU0NSSVBUSU9OX0NIQVRH",
            "Uk9VUBD+ChIqCiVFR0VDX1JFUV9DQU5DRUxTVUJTQ1JJUFRJT05fQ0hBVEdS",
            "T1VQEP8KEh4KGUVHRUNfUkVRX0lOVklURV9DSEFUR1JPVVAQgAsSHgoZRUdF",
            "Q19BQ0tfSU5WSVRFX0NIQVRHUk9VUBCBCxIcChdFR0VDX1JFUV9LSUNLX0NI",
            "QVRHUk9VUBCCCxIcChdFR0VDX0FDS19LSUNLX0NIQVRHUk9VUBCDCxIfChpF",
            "R0VDX1JFUV9DSEFUR1JPVVBfVE9fVEVBTRCqCxIfChpFR0VDX0FDS19DSEFU",
            "R1JPVVBfVE9fVEVBTRCrCxIlCiBFR0VDX1JFUV9JTlRFTlNJRllMRVZFTF9U",
            "T19FUVVJUBDcCxIlCiBFR0VDX0FDS19JTlRFTlNJRllMRVZFTF9UT19FUVVJ",
            "UBDdCxIbChZFR0VDX1JFUV9IT0xFX1RPX0VRVUlQEN4LEhsKFkVHRUNfQUNL",
            "X0hPTEVfVE9fRVFVSVAQ3wsSIQocRUdFQ19SRVFfSU5MQVlTVE9ORV9UT19F",
            "UVVJUBDgCxIhChxFR0VDX0FDS19JTkxBWVNUT05FX1RPX0VRVUlQEOELEiMK",
            "HkVHRUNfUkVRX0VMRU1FTlRMRVZFTF9UT19FUVVJUBDiCxIjCh5FR0VDX0FD",
            "S19FTEVNRU5UTEVWRUxfVE9fRVFVSVAQ4wsSFAoPRUdFQ19XRUFSX0VRVUlQ",
            "EOQLEhcKEkVHRUNfVEFLRU9GRl9FUVVJUBDlCxIcChdFR0VDX1JFUV9TRVRf",
            "RklHSFRfSEVSTxDwCxIfChpFR0VDX1JFUV9TV0lUQ0hfRklHSFRfSEVSTxDx",
            "CxIaChVFR0VDX1JFUV9NSU5JTkdfVElUTEUQwAwSGgoVRUdFQ19BQ0tfTUlO",
            "SU5HX1RJVExFEMEMEhcKEkVHRUNfUkVRX1NFTkRfTUFJTBCkDRIXChJFR0VD",
            "X1JFUV9EUkFXX01BSUwQpQ0SGQoURUdFQ19SRVFfREVMRVRFX01BSUwQpg0S",
            "IAobRUdNSV9BQ0tfQ0xPTkVfT0JKRUNUX0VOVFJZEIgOEiAKG0VHTUlfQUNL",
            "X0NMT05FX09CSkVDVF9MRUFWRRCJDhIpCiRFR01JX0FDS19DTE9ORV9PQkpF",
            "Q1RfUFJPUEVSVFlfRU5UUlkQig4SJwoiRUdNSV9BQ0tfQ0xPTkVfT0JKRUNU",
            "X1JFQ09SRF9FTlRSWRCLDhIgChtFR01JX0FDS19DTE9ORV9QUk9QRVJUWV9J",
            "TlQQkg4SIgodRUdNSV9BQ0tfQ0xPTkVfUFJPUEVSVFlfRkxPQVQQkw4SIwoe",
            "RUdNSV9BQ0tfQ0xPTkVfUFJPUEVSVFlfU1RSSU5HEJQOEiMKHkVHTUlfQUNL",
            "X0NMT05FX1BST1BFUlRZX09CSkVDVBCWDhIYChNFR01JX1JFUVNXSUNIU0VS",
            "VkVSELAOEhgKE0VHTUlfQUNLU1dJQ0hTRVJWRVIQsQ4SGQoURUdNSV9SRVFf",
            "Q1JFQVRFX1RFQU0QxA4SGQoURUdNSV9BQ0tfQ1JFQVRFX1RFQU0QxQ4SFwoS",
            "RUdNSV9SRVFfSk9JTl9URUFNEMYOEhcKEkVHTUlfQUNLX0pPSU5fVEVBTRDH",
            "DhIYChNFR01JX1JFUV9MRUFWRV9URUFNEMgOEhgKE0VHTUlfQUNLX0xFQVZF",
            "X1RFQU0QyQ4SGQoURUdNSV9SRVFfSU5WSVRFX1RFQU0Qyg4SHAoXRUdNSV9S",
            "RVFfT1BSTUVNQkVSX1RFQU0Qyw4SHAoXRUdNSV9BQ0tfT1BSTUVNQkVSX1RF",
            "QU0QzA4SHwoaRUdNSV9SRVFfVEVBTV9FTlRFUl9FQ1RZUEUQzQ4SHwoaRUdN",
            "SV9BQ0tfVEVBTV9FTlRFUl9FQ1RZUEUQzg4SGwoWRUdNSV9SRVFfTUFQX0dS",
            "SURfSU5GTxDsDhIbChZFR01JX0FDS19NQVBfR1JJRF9JTkZPEO0OEhoKFUVH",
            "TUlfUkVRX0JJR19NQVBfSU5GTxDuDhIaChVFR01JX0FDS19CSUdfTUFQX0lO",
            "Rk8Q7w4SGwoWRUdNSV9SRVFfSE9MRF9NQVBfR1JJRBD2DhIbChZFR01JX0FD",
            "S19IT0xEX01BUF9HUklEEPcOEiAKG0VHTUlfUkVRX0xFQVZFX01TR19NQVBf",
            "R1JJRBD4DhIgChtFR01JX0FDS19MRUFWRV9NU0dfTUFQX0dSSUQQ+Q4SIAob",
            "RUdNSV9SRVFfR0VUX01BUF9HUklEX0FXQVJEEPoOEiAKG0VHTUlfQUNLX0dF",
            "VF9NQVBfR1JJRF9BV0FSRBD7DhIeChlFR01JX1JFUV9NQVBfR1JJRF9IVU5U",
            "SU5HEPwOEh4KGUVHTUlfQUNLX01BUF9HUklEX0hVTlRJTkcQ/Q4SHwoaRUdN",
            "SV9SRVFfTUFQX0dSSURfS0lOR19XQVIQ/g4SHwoaRUdNSV9BQ0tfTUFQX0dS",
            "SURfS0lOR19XQVIQ/w4SHgoZRUdNSV9SRVFfQ01EX1BST1BFUlRZX0lOVBCQ",
            "ThIeChlFR01JX1JFUV9DTURfUFJPUEVSVFlfU1RSEJFOEiEKHEVHTUlfUkVR",
            "X0NNRF9QUk9QRVJUWV9PQkpFQ1QQkk4SIAobRUdNSV9SRVFfQ01EX1BST1BF",
            "UlRZX0ZMT0FUEJNOEhwKF0VHTUlfUkVRX0NNRF9SRUNPUkRfSU5UEJROEhwK",
            "F0VHTUlfUkVRX0NNRF9SRUNPUkRfU1RSEJVOEh8KGkVHTUlfUkVRX0NNRF9S",
            "RUNPUkRfT0JKRUNUEJZOEh4KGUVHTUlfUkVRX0NNRF9SRUNPUkRfRkxPQVQQ",
            "l04SGAoTRUdNSV9SRVFfQ01EX05PUk1BTBCYThIhChxFR01JX1JFUV9RVUVS",
            "WV9TRVJWRVJfU1RBVFVTENhPEhwKFkVHTUlfUkVRX0JVWV9GT1JNX1NIT1AQ",
            "oJwBEhwKFkVHTUlfQUNLX0JVWV9GT1JNX1NIT1AQoZwBEiAKGkVHTUlfUkVR",
            "X01PVkVfQlVJTERfT0JKRUNUEKKcARIgChpFR01JX0FDS19NT1ZFX0JVSUxE",
            "X09CSkVDVBCjnAESGwoVRUdNSV9SRVFfVVBfQlVJTERfTFZMEIWdARIaChRF",
            "R01JX1JFUV9DUkVBVEVfSVRFTRCGnQESHAoWRUdNSV9SRVFfQlVJTERfT1BF",
            "UkFURRCHnQESHgoYRUdNSV9SRVFfU0VBUkNIX1RPX1NIQVJFELDqARIeChhF",
            "R01JX0FDS19TRUFSQ0hfVE9fU0hBUkUQseoBEh0KF0VHTUlfUkVRX1NIQVJF",
            "X1RPX0FUQVJUELLqARIdChdFR01JX0FDS19TSEFSRV9UT19BVEFSVBCz6gEq",
            "wAEKCkVTa2lsbFR5cGUSFAoQRVNUX0JSSUVGX1NJTkdMRRAAEhMKD0VTVF9C",
            "UklFRl9HUk9VUBABEhUKEUVTVF9CVUxMRVRfU0lOR0xFEAISFgoSRVNUX0JV",
            "TExFVF9SRUJPVU5EEAMSEwoPRVNUX0JVTExFVF9CT01CEAQSFQoRRVNUX1RB",
            "UkdFVF9TSU5HTEUQBRIUChBFU1RfVEFSR0VUX0dST1VQEAYSFgoSRVNUX1BP",
            "U0lUSU9OX0dST1VQEAcqUgoJRUl0ZW1UeXBlEg0KCUVJVF9FUVVJUBAAEgsK",
            "B0VJVF9HRU0QARIMCghFSVRfSVRFTRACEgwKCEVJVF9DQVJEEAMSDQoJRUlU",
            "X1RPS0VOEAQqkQEKEUVHYW1lRXF1aXBTdWJUeXBlEhQKEEVRVUlQVFlQRV9X",
            "RUFQT04QABIUChBFUVVJUFRZUEVfSEVMTUVUEAESEwoPRVFVSVBUWVBFX0FS",
            "TU9SEAISEwoPRVFVSVBUWVBFX1dSSVNUEAMSEgoORVFVSVBUWVBFX1BBTlQQ",
            "BBISCg5FUVVJUFRZUEVfQk9PVBAFKrIBCg9FR2FtZUdlbVN1YlR5cGUSFAoQ",
            "RUdHU1RZUEVfR0VNX0FUSxAAEhQKEEVHR1NUWVBFX0dFTV9ERUYQARIVChFF",
            "R0dTVFlQRV9HRU1fRklSRRADEhYKEkVHR1NUWVBFX0dFTV9MSUdIVBAEEhUK",
            "EUVHR1NUWVBFX0dFTV9XSU5EEAUSFAoQRUdHU1RZUEVfR0VNX0lDRRAGEhcK",
            "E0VHR1NUWVBFX0dFTV9QT0lTT04QByrNAQoQRUdhbWVJdGVtU3ViVHlwZRIT",
            "Cg9FR0lUX0lURU1fV0FURVIQABIVChFFR0lUX0lURU1fRElBTU9ORBABEhYK",
            "EkVHSVRfSVRFTV9DVVJSRU5DWRACEhEKDUVHSVRfSVRFTV9FWFAQAxIQCgxF",
            "R0lUX0lURU1fSFAQBBIQCgxFR0lUX0lURU1fTVAQBRIQCgxFR0lUX0lURU1f",
            "U1AQBhISCg5FR0lUX0lURU1fUEFDSxAHEhgKFEVHSVRfSVRFTV9NRU1PUllf",
            "UE9TEAgqYwoQRUdhbWVDYXJkU3ViVHlwZRIQCgxFR0NTVF9VTktOT1cQABIS",
            "Cg5FR0NTVF9TVFJFTkdUSBABEhEKDUVHQ1NUX0FHSUxJVFkQAhIWChJFR0NT",
            "VF9JTlRFTExJR0VOQ0UQAyqOAQoRRUdhbWVUb2tlblN1YlR5cGUSFgoSRUdU",
            "U1RfVE9LRU5fUkVCT1JOEAASGAoURUdUU1RfVE9LRU5fUE9TSVRJT04QARIW",
            "ChJFR1RTVF9UT0tFTl9CT1VOVFkQAhIYChRFR1RTVF9UT0tFTl9BQ1RJVklU",
            "WRADEhUKEUVHVFNUX1RPS0VOX0JVSUxEEAQqZQoURUdhbWVJdGVtRXhwaXJl",
            "ZFR5cGUSDgoKRUdJRVRfTk9ORRAAEhMKD0VHSUVUX1VTRV9USU1FUxABEhMK",
            "D0VHSUVUX1JFQUxfVElNRRACEhMKD0VHSUVUX0VORF9JTkRFWBADKlkKEkVE",
            "cmF3RHJvcEl0ZW1TdGF0ZRIVChFFX0RSQVdfU1RBVEVfTk9ORRAAEhUKEUVf",
            "RFJBV19TVEFURV9HQUlOEAESFQoRRV9EUkFXX1NUQVRFX1JFQ1YQAipzCg9F",
            "R3VpbGRQb3dlclR5cGUSGwoXR1VJTERfUE9XRVJfVFlQRV9OT1JNQUwQABIj",
            "Ch9HVUlMRF9QT1dFUl9UWVBFX1ZJQ0VfUFJFU0lERU5UEAESHgoaR1VJTERf",
            "UE9XRVJfVFlQRV9QUkVTSURFTlQQAipWCgpFVGFza1N0YXRlEhMKD1RBU0tf",
            "SU5fUFJPQ0VTUxAAEg0KCVRBU0tfRE9ORRABEhMKD1RBU0tfRFJBV19BV0FS",
            "RBACEg8KC1RBU0tfRklOSVNIEAMqqQIKCUVUYXNrVHlwZRIgChxUQVNLX0xF",
            "VkVMX1VQREFURV9TT01FX0xFVkVMEAASFAoQVEFTS19QQVNTX0VDVFlQRRAB",
            "EhoKFlRBU0tfUEFTU19FQ1RZUEVfQ09VTlQQAhIkCiBUQVNLX1BBU1NfU09N",
            "RV9UWVBFX0VDVFlQRV9DT1VOVBADEhsKF1RBU0tfVVBEQVRFX1NLSUxMX0NP",
            "VU5UEAQSFgoSVEFTS19DT05TVU1FX01PTkVZEAUSGAoUVEFTS19DT05TVU1F",
            "X0RJQU1PTkQQBhIUChBUQVNLX0FSRU5BX0NPVU5UEAcSGwoXVEFTS19LSUxM",
            "X01PTlNURVJfQ09VTlQQCBIgChxUQVNLX0tJTExfU09NRV9NT05TVEVSX0NP",
            "VU5UEAkqdgoIRVBWUFR5cGUSDAoIUFZQX0hPTUUQABISCg5QVlBfSU5ESVZJ",
            "RFVBTBABEgwKCFBWUF9ET1RBEAISEAoMUFZQX1NVUlZJVkFMEAMSEQoNUFZQ",
            "X0dVSUxEX1dBUhAEEhUKEVBWUF9HVUlMRF9EVU5HRU9OEAUqcwoJRVNob3BU",
            "eXBlEg4KCkVTVF9VTktOT1cQABIQCgxFU1RfQlVJTERJTkcQARIMCghFU1Rf",
            "R09MRBACEgwKCEVTVF9JVEVNEAMSDQoJRVNUX0VRVUlQEAUSCwoHRVNUX0dF",
            "TRAGEgwKCEVTVF9DQVJEEAcqiwEKCUVSYW5rVHlwZRIOCgpFUlRfVU5LTk9X",
            "EAASFAoQRVJUX1BMQVlFUl9MRVZFTBABEhMKD0VSVF9GSUdIVF9WQUxVRRAC",
            "EhQKEEVSVF9QTEFZRVJfTU9ORVkQAxITCg9FUlRfR1VJTERfTEVWRUwQBBIY",
            "ChRFUlRfR1VJTERfS0lOR1NPVVJDRRAFKkcKCEVOUENUeXBlEhMKD0VOUENU",
            "WVBFX05PUk1BTBAAEhEKDUVOUENUWVBFX0hFUk8QARITCg9FTlBDVFlQRV9U",
            "VVJSRVQQAipSCgtFVEFSR0VUVHlwZRIVChFFVEFSR0VUVFlQRV9FTkVNWRAA",
            "EhQKEEVUQVJHRVRUWVBFX1NFTEYQARIWChJFVEFSR0VUVFlQRV9GUklFTkQQ",
            "AipYCg1FUHJvcGVydHlUeXBlEg4KCkVQVF9VTktOT1cQABIQCgxFUFRfU1RS",
            "RU5HVEgQARIPCgtFUFRfQUdJTElUWRACEhQKEEVQVF9JTlRFTExJR0VOQ0UQ",
            "AyqeAQoQRUdhbWVFbGVtZW50VHlwZRIVChFFRUxFTUVOVFRZUEVfRklSRRAA",
            "EhYKEkVFTEVNRU5UVFlQRV9MSUdIVBABEhUKEUVFTEVNRU5UVFlQRV9XSU5E",
            "EAISFAoQRUVMRU1FTlRUWVBFX0lDRRADEhcKE0VFTEVNRU5UVFlQRV9QT0lT",
            "T04QBBIVChFFRUxFTUVOVFRZUEVfREFSSxAFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::NFMsg.EGameEventCode), typeof(global::NFMsg.ESynMsgID), typeof(global::NFMsg.EGameMsgID), typeof(global::NFMsg.ESkillType), typeof(global::NFMsg.EItemType), typeof(global::NFMsg.EGameEquipSubType), typeof(global::NFMsg.EGameGemSubType), typeof(global::NFMsg.EGameItemSubType), typeof(global::NFMsg.EGameCardSubType), typeof(global::NFMsg.EGameTokenSubType), typeof(global::NFMsg.EGameItemExpiredType), typeof(global::NFMsg.EDrawDropItemState), typeof(global::NFMsg.EGuildPowerType), typeof(global::NFMsg.ETaskState), typeof(global::NFMsg.ETaskType), typeof(global::NFMsg.EPVPType), typeof(global::NFMsg.EShopType), typeof(global::NFMsg.ERankType), typeof(global::NFMsg.ENPCType), typeof(global::NFMsg.ETARGETType), typeof(global::NFMsg.EPropertyType), typeof(global::NFMsg.EGameElementType), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///events
  /// </summary>
  public enum EGameEventCode {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_SUCCESS")] EGEC_SUCCESS = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_UNKOWN_ERROR")] EGEC_UNKOWN_ERROR = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACCOUNT_EXIST")] EGEC_ACCOUNT_EXIST = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACCOUNTPWD_INVALID")] EGEC_ACCOUNTPWD_INVALID = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACCOUNT_USING")] EGEC_ACCOUNT_USING = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACCOUNT_LOCKED")] EGEC_ACCOUNT_LOCKED = 5,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACCOUNT_SUCCESS")] EGEC_ACCOUNT_SUCCESS = 6,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_VERIFY_KEY_SUCCESS")] EGEC_VERIFY_KEY_SUCCESS = 7,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_VERIFY_KEY_FAIL")] EGEC_VERIFY_KEY_FAIL = 8,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_SELECTSERVER_SUCCESS")] EGEC_SELECTSERVER_SUCCESS = 9,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_SELECTSERVER_FAIL")] EGEC_SELECTSERVER_FAIL = 10,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_EXIST")] EGEC_CHARACTER_EXIST = 110,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_SVRZONEID_INVALID")] EGEC_SVRZONEID_INVALID = 111,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_NUMOUT")] EGEC_CHARACTER_NUMOUT = 112,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_INVALID")] EGEC_CHARACTER_INVALID = 113,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_NOTEXIST")] EGEC_CHARACTER_NOTEXIST = 114,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_USING")] EGEC_CHARACTER_USING = 115,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_CHARACTER_LOCKED")] EGEC_CHARACTER_LOCKED = 116,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ZONE_OVERLOAD")] EGEC_ZONE_OVERLOAD = 117,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_NOT_ONLINE")] EGEC_NOT_ONLINE = 118,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ALREAY_IN_TEAM")] EGEC_ALREAY_IN_TEAM = 119,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_TEAM_INVITE")] EGEC_INVALID_TEAM_INVITE = 120,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_TEAM_FULL")] EGEC_TEAM_FULL = 121,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_MAIL_UPDATE_ERROR")] EGEC_MAIL_UPDATE_ERROR = 122,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_MAIL_TONAME_INVALID")] EGEC_MAIL_TONAME_INVALID = 123,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_MAIL_DELETE_ERROR")] EGEC_MAIL_DELETE_ERROR = 124,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_MAIL_TOWNAME_EQUAL")] EGEC_MAIL_TOWNAME_EQUAL = 125,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_LACK_MONEY")] EGEC_LACK_MONEY = 126,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_FULL_PACKAGE")] EGEC_FULL_PACKAGE = 127,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_ITEM")] EGEC_INVALID_ITEM = 128,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_CONSIGNMENT")] EGEC_INVALID_CONSIGNMENT = 129,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_NOT_ENOUGH_VIP")] EGEC_NOT_ENOUGH_VIP = 130,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_NEED_LEVEL")] EGEC_NEED_LEVEL = 131,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_MAX_FRIEND_LIST")] EGEC_MAX_FRIEND_LIST = 132,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_MAX_ENEMY_LIST")] EGEC_MAX_ENEMY_LIST = 133,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_MAX_GANGS_LSIT")] EGEC_MAX_GANGS_LSIT = 134,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_LIMITS_TO_RIGHTS")] EGEC_LIMITS_TO_RIGHTS = 135,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_GANGS_NAME")] EGEC_INVALID_GANGS_NAME = 136,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REPEAT_ENTER_GANGS")] EGEC_REPEAT_ENTER_GANGS = 137,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_GANGSMEMBER")] EGEC_INVALID_GANGSMEMBER = 138,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_MASTER_LEAVE_GANGS")] EGEC_MASTER_LEAVE_GANGS = 139,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_GANGS_TITLE_OUTOF")] EGEC_GANGS_TITLE_OUTOF = 140,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ENTER_GATEWAY_FAILD")] EGEC_ENTER_GATEWAY_FAILD = 141,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_NO_SERVER4ZONE")] EGEC_NO_SERVER4ZONE = 142,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_INVALID_SKILL")] EGEC_INVALID_SKILL = 143,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_CREATE_GUILD_SUCCESS")] EGEC_CREATE_GUILD_SUCCESS = 200,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_JOIN_GUILD_SUCCESS")] EGEC_JOIN_GUILD_SUCCESS = 201,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_LEAVE_GUILD_SUCCESS")] EGEC_LEAVE_GUILD_SUCCESS = 202,
  }

  public enum ESynMsgID {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ESMI_UNKNOW")] ESMI_UNKNOW = 0,
  }

  public enum EGameMsgID {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_UNKNOW")] EGMI_UNKNOW = 0,
    /// <summary>
    /// for events
    /// </summary>
    [pbr::OriginalName("EGMI_EVENT_RESULT")] EGMI_EVENT_RESULT = 1,
    /// <summary>
    /// for events
    /// </summary>
    [pbr::OriginalName("EGMI_EVENT_TRANSPOND")] EGMI_EVENT_TRANSPOND = 2,
    /// <summary>
    /// want to close some one
    /// </summary>
    [pbr::OriginalName("EGMI_CLOSE_SOCKET")] EGMI_CLOSE_SOCKET = 3,
    [pbr::OriginalName("EGMI_WTM_WORLD_REGISTERED")] EGMI_WTM_WORLD_REGISTERED = 10,
    [pbr::OriginalName("EGMI_WTM_WORLD_UNREGISTERED")] EGMI_WTM_WORLD_UNREGISTERED = 11,
    [pbr::OriginalName("EGMI_WTM_WORLD_REFRESH")] EGMI_WTM_WORLD_REFRESH = 12,
    [pbr::OriginalName("EGMI_LTM_LOGIN_REGISTERED")] EGMI_LTM_LOGIN_REGISTERED = 20,
    [pbr::OriginalName("EGMI_LTM_LOGIN_UNREGISTERED")] EGMI_LTM_LOGIN_UNREGISTERED = 21,
    [pbr::OriginalName("EGMI_LTM_LOGIN_REFRESH")] EGMI_LTM_LOGIN_REFRESH = 22,
    [pbr::OriginalName("EGMI_PTWG_PROXY_REGISTERED")] EGMI_PTWG_PROXY_REGISTERED = 30,
    [pbr::OriginalName("EGMI_PTWG_PROXY_UNREGISTERED")] EGMI_PTWG_PROXY_UNREGISTERED = 31,
    [pbr::OriginalName("EGMI_PTWG_PROXY_REFRESH")] EGMI_PTWG_PROXY_REFRESH = 32,
    [pbr::OriginalName("EGMI_GTW_GAME_REGISTERED")] EGMI_GTW_GAME_REGISTERED = 40,
    [pbr::OriginalName("EGMI_GTW_GAME_UNREGISTERED")] EGMI_GTW_GAME_UNREGISTERED = 41,
    [pbr::OriginalName("EGMI_GTW_GAME_REFRESH")] EGMI_GTW_GAME_REFRESH = 42,
    [pbr::OriginalName("EGMI_DTW_DB_REGISTERED")] EGMI_DTW_DB_REGISTERED = 60,
    [pbr::OriginalName("EGMI_DTW_DB_UNREGISTERED")] EGMI_DTW_DB_UNREGISTERED = 61,
    [pbr::OriginalName("EGMI_DTW_DB_REFRESH")] EGMI_DTW_DB_REFRESH = 62,
    [pbr::OriginalName("EGMI_STS_NET_INFO")] EGMI_STS_NET_INFO = 70,
    [pbr::OriginalName("EGMI_STS_SERVER_REPORT")] EGMI_STS_SERVER_REPORT = 90,
    [pbr::OriginalName("EGMI_STS_HEART_BEAT")] EGMI_STS_HEART_BEAT = 100,
    /// <summary>
    ///////////////////////////////////////////////////////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LOGIN")] EGMI_REQ_LOGIN = 101,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LOGIN")] EGMI_ACK_LOGIN = 102,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LOGOUT")] EGMI_REQ_LOGOUT = 103,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_WORLD_LIST")] EGMI_REQ_WORLD_LIST = 110,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_WORLD_LIST")] EGMI_ACK_WORLD_LIST = 111,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CONNECT_WORLD")] EGMI_REQ_CONNECT_WORLD = 112,
    [pbr::OriginalName("EGMI_ACK_CONNECT_WORLD")] EGMI_ACK_CONNECT_WORLD = 113,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_KICK_CLIENT_INWORLD")] EGMI_REQ_KICK_CLIENT_INWORLD = 114,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CONNECT_KEY")] EGMI_REQ_CONNECT_KEY = 120,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CONNECT_KEY")] EGMI_ACK_CONNECT_KEY = 122,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SELECT_SERVER")] EGMI_REQ_SELECT_SERVER = 130,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_SELECT_SERVER")] EGMI_ACK_SELECT_SERVER = 131,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_ROLE_LIST")] EGMI_REQ_ROLE_LIST = 132,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_ROLE_LIST")] EGMI_ACK_ROLE_LIST = 133,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CREATE_ROLE")] EGMI_REQ_CREATE_ROLE = 134,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_DELETE_ROLE")] EGMI_REQ_DELETE_ROLE = 135,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_RECOVER_ROLE")] EGMI_REQ_RECOVER_ROLE = 136,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LOAD_ROLE_DATA")] EGMI_REQ_LOAD_ROLE_DATA = 140,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LOAD_ROLE_DATA")] EGMI_ACK_LOAD_ROLE_DATA = 141,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SAVE_ROLE_DATA")] EGMI_REQ_SAVE_ROLE_DATA = 142,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_SAVE_ROLE_DATA")] EGMI_ACK_SAVE_ROLE_DATA = 143,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LOAD_OBJ_DATA")] EGMI_REQ_LOAD_OBJ_DATA = 144,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LOAD_OBJ_DATA")] EGMI_ACK_LOAD_OBJ_DATA = 145,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SAVE_OBJ_DATA")] EGMI_REQ_SAVE_OBJ_DATA = 146,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_SAVE_OBJ_DATA")] EGMI_ACK_SAVE_OBJ_DATA = 147,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_ENTER_GAME")] EGMI_REQ_ENTER_GAME = 150,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_ENTER_GAME")] EGMI_ACK_ENTER_GAME = 151,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LEAVE_GAME")] EGMI_REQ_LEAVE_GAME = 152,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LEAVE_GAME")] EGMI_ACK_LEAVE_GAME = 153,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SWAP_GAME")] EGMI_REQ_SWAP_GAME = 154,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SWAP_SCENE")] EGMI_REQ_SWAP_SCENE = 155,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_SWAP_SCENE")] EGMI_ACK_SWAP_SCENE = 156,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SWAP_HOME_SCENE")] EGMI_REQ_SWAP_HOME_SCENE = 157,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_SWAP_HOME_SCENE")] EGMI_ACK_SWAP_HOME_SCENE = 158,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_ENTER_GAME_FINISH")] EGMI_REQ_ENTER_GAME_FINISH = 159,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_ENTER_GAME_FINISH")] EGMI_ACK_ENTER_GAME_FINISH = 160,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_ACK_RELIVE")] EGMI_REQ_ACK_RELIVE = 180,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OBJECT_ENTRY")] EGMI_ACK_OBJECT_ENTRY = 200,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OBJECT_LEAVE")] EGMI_ACK_OBJECT_LEAVE = 201,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OBJECT_PROPERTY_ENTRY")] EGMI_ACK_OBJECT_PROPERTY_ENTRY = 202,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OBJECT_RECORD_ENTRY")] EGMI_ACK_OBJECT_RECORD_ENTRY = 203,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_PROPERTY_INT")] EGMI_ACK_PROPERTY_INT = 210,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_PROPERTY_FLOAT")] EGMI_ACK_PROPERTY_FLOAT = 211,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_PROPERTY_STRING")] EGMI_ACK_PROPERTY_STRING = 212,
    /// <summary>
    ///EGMI_ACK_PROPERTY_DOUBLE					= 213;			//
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_PROPERTY_OBJECT")] EGMI_ACK_PROPERTY_OBJECT = 214,
    [pbr::OriginalName("EGMI_ACK_PROPERTY_VECTOR2")] EGMI_ACK_PROPERTY_VECTOR2 = 215,
    [pbr::OriginalName("EGMI_ACK_PROPERTY_VECTOR3")] EGMI_ACK_PROPERTY_VECTOR3 = 216,
    [pbr::OriginalName("EGMI_ACK_ADD_ROW")] EGMI_ACK_ADD_ROW = 220,
    [pbr::OriginalName("EGMI_ACK_REMOVE_ROW")] EGMI_ACK_REMOVE_ROW = 221,
    [pbr::OriginalName("EGMI_ACK_SWAP_ROW")] EGMI_ACK_SWAP_ROW = 222,
    [pbr::OriginalName("EGMI_ACK_RECORD_INT")] EGMI_ACK_RECORD_INT = 223,
    [pbr::OriginalName("EGMI_ACK_RECORD_FLOAT")] EGMI_ACK_RECORD_FLOAT = 224,
    /// <summary>
    ///EGMI_ACK_RECORD_DOUBLE					= 225;
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_RECORD_STRING")] EGMI_ACK_RECORD_STRING = 226,
    [pbr::OriginalName("EGMI_ACK_RECORD_OBJECT")] EGMI_ACK_RECORD_OBJECT = 227,
    [pbr::OriginalName("EGMI_ACK_RECORD_VECTOR2")] EGMI_ACK_RECORD_VECTOR2 = 228,
    [pbr::OriginalName("EGMI_ACK_RECORD_VECTOR3")] EGMI_ACK_RECORD_VECTOR3 = 229,
    [pbr::OriginalName("EGMI_ACK_RECORD_CLEAR")] EGMI_ACK_RECORD_CLEAR = 250,
    [pbr::OriginalName("EGMI_ACK_RECORD_SORT")] EGMI_ACK_RECORD_SORT = 251,
    [pbr::OriginalName("EGMI_ACK_DATA_FINISHED")] EGMI_ACK_DATA_FINISHED = 260,
    [pbr::OriginalName("EGMI_REQ_START_OPPNENT")] EGMI_REQ_START_OPPNENT = 1220,
    [pbr::OriginalName("EGMI_ACK_START_OPPNENT")] EGMI_ACK_START_OPPNENT = 1221,
    [pbr::OriginalName("EGMI_REQ_END_OPPNENT")] EGMI_REQ_END_OPPNENT = 1222,
    [pbr::OriginalName("EGMI_ACK_END_OPPNENT")] EGMI_ACK_END_OPPNENT = 1223,
    [pbr::OriginalName("EGMI_REQ_SEARCH_OPPNENT")] EGMI_REQ_SEARCH_OPPNENT = 1224,
    [pbr::OriginalName("EGMI_ACK_SEARCH_OPPNENT")] EGMI_ACK_SEARCH_OPPNENT = 1225,
    [pbr::OriginalName("EGMI_REQ_ADJUST_GAMBLE")] EGMI_REQ_ADJUST_GAMBLE = 1226,
    [pbr::OriginalName("EGMI_REQ_MOVE")] EGMI_REQ_MOVE = 1230,
    [pbr::OriginalName("EGMI_ACK_MOVE")] EGMI_ACK_MOVE = 1231,
    [pbr::OriginalName("EGMI_REQ_MOVE_IMMUNE")] EGMI_REQ_MOVE_IMMUNE = 1232,
    [pbr::OriginalName("EGMI_ACK_MOVE_IMMUNE")] EGMI_ACK_MOVE_IMMUNE = 1233,
    [pbr::OriginalName("EGMI_REQ_STATE_SYNC")] EGMI_REQ_STATE_SYNC = 1234,
    [pbr::OriginalName("EGMI_ACK_STATE_SYNC")] EGMI_ACK_STATE_SYNC = 1235,
    [pbr::OriginalName("EGMI_REQ_SKILL_OBJECTX")] EGMI_REQ_SKILL_OBJECTX = 1240,
    [pbr::OriginalName("EGMI_ACK_SKILL_OBJECTX")] EGMI_ACK_SKILL_OBJECTX = 1241,
    [pbr::OriginalName("EGMI_REQ_SKILL_POS")] EGMI_REQ_SKILL_POS = 1242,
    [pbr::OriginalName("EGMI_ACK_SKILL_POS")] EGMI_ACK_SKILL_POS = 1243,
    [pbr::OriginalName("EGMI_REQ_ITEM_OBJECT")] EGMI_REQ_ITEM_OBJECT = 1244,
    [pbr::OriginalName("EGMI_ACK_ITEM_OBJECT")] EGMI_ACK_ITEM_OBJECT = 1245,
    [pbr::OriginalName("EGMI_REQ_ITEM_POS")] EGMI_REQ_ITEM_POS = 1246,
    [pbr::OriginalName("EGMI_ACK_ITEM_POS")] EGMI_ACK_ITEM_POS = 1247,
    [pbr::OriginalName("EGMI_REQ_CHAT")] EGMI_REQ_CHAT = 1250,
    [pbr::OriginalName("EGMI_ACK_CHAT")] EGMI_ACK_CHAT = 1251,
    [pbr::OriginalName("EGMI_REQ_SALE_ITEM")] EGMI_REQ_SALE_ITEM = 1252,
    [pbr::OriginalName("EGMI_REQ_SPLIT_ITEM")] EGMI_REQ_SPLIT_ITEM = 1253,
    [pbr::OriginalName("EGMI_REQ_PRODUCE_ITEM")] EGMI_REQ_PRODUCE_ITEM = 1254,
    [pbr::OriginalName("EGMI_REQ_PICK_ITEM")] EGMI_REQ_PICK_ITEM = 1255,
    [pbr::OriginalName("EGMI_REQ_ACCEPT_TASK")] EGMI_REQ_ACCEPT_TASK = 1256,
    [pbr::OriginalName("EGMI_REQ_COMPELETE_TASK")] EGMI_REQ_COMPELETE_TASK = 1257,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_ONLINE_NOTIFY")] EGMI_ACK_ONLINE_NOTIFY = 1290,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OFFLINE_NOTIFY")] EGMI_ACK_OFFLINE_NOTIFY = 1291,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CREATE_GUILD")] EGMI_REQ_CREATE_GUILD = 1300,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CREATE_GUILD")] EGMI_ACK_CREATE_GUILD = 1301,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_JOIN_GUILD")] EGMI_REQ_JOIN_GUILD = 1302,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_JOIN_GUILD")] EGMI_ACK_JOIN_GUILD = 1303,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LEAVE_GUILD")] EGMI_REQ_LEAVE_GUILD = 1304,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LEAVE_GUILD")] EGMI_ACK_LEAVE_GUILD = 1305,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_OPR_GUILD")] EGMI_REQ_OPR_GUILD = 1306,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OPR_GUILD")] EGMI_ACK_OPR_GUILD = 1307,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SEARCH_GUILD")] EGMI_REQ_SEARCH_GUILD = 1308,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_SEARCH_GUILD")] EGMI_ACK_SEARCH_GUILD = 1309,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_OPR_GUILDINFO")] EGMI_REQ_OPR_GUILDINFO = 1310,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OPR_GUILDINFO")] EGMI_ACK_OPR_GUILDINFO = 1311,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_GUILDECTYPEINFO")] EGMI_REQ_GUILDECTYPEINFO = 1312,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_GUILDECTYPEINFO")] EGMI_ACK_GUILDECTYPEINFO = 1313,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_SET_GUILDECTYPEINFO")] EGMI_SET_GUILDECTYPEINFO = 1314,
    /// <summary>
    /// 
    /// </summary>
    [pbr::OriginalName("EGMI_ReqEnterGuildEctype")] EGMI_ReqEnterGuildEctype = 1315,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_CREATE_CHATGROUP")] EGEC_REQ_CREATE_CHATGROUP = 1400,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_CREATE_CHATGROUP")] EGEC_ACK_CREATE_CHATGROUP = 1401,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_JOIN_CHATGROUP")] EGEC_REQ_JOIN_CHATGROUP = 1402,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_JOIN_CHATGROUP")] EGEC_ACK_JOIN_CHATGROUP = 1403,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_LEAVE_CHATGROUP")] EGEC_REQ_LEAVE_CHATGROUP = 1404,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_LEAVE_CHATGROUP")] EGEC_ACK_LEAVE_CHATGROUP = 1405,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_SUBSCRIPTION_CHATGROUP")] EGEC_REQ_SUBSCRIPTION_CHATGROUP = 1406,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_CANCELSUBSCRIPTION_CHATGROUP")] EGEC_REQ_CANCELSUBSCRIPTION_CHATGROUP = 1407,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_INVITE_CHATGROUP")] EGEC_REQ_INVITE_CHATGROUP = 1408,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_INVITE_CHATGROUP")] EGEC_ACK_INVITE_CHATGROUP = 1409,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_KICK_CHATGROUP")] EGEC_REQ_KICK_CHATGROUP = 1410,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_KICK_CHATGROUP")] EGEC_ACK_KICK_CHATGROUP = 1411,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_CHATGROUP_TO_TEAM")] EGEC_REQ_CHATGROUP_TO_TEAM = 1450,
    /// <summary>
    ///	
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_CHATGROUP_TO_TEAM")] EGEC_ACK_CHATGROUP_TO_TEAM = 1451,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_INTENSIFYLEVEL_TO_EQUIP")] EGEC_REQ_INTENSIFYLEVEL_TO_EQUIP = 1500,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_INTENSIFYLEVEL_TO_EQUIP")] EGEC_ACK_INTENSIFYLEVEL_TO_EQUIP = 1501,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_HOLE_TO_EQUIP")] EGEC_REQ_HOLE_TO_EQUIP = 1502,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_HOLE_TO_EQUIP")] EGEC_ACK_HOLE_TO_EQUIP = 1503,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_INLAYSTONE_TO_EQUIP")] EGEC_REQ_INLAYSTONE_TO_EQUIP = 1504,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_INLAYSTONE_TO_EQUIP")] EGEC_ACK_INLAYSTONE_TO_EQUIP = 1505,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_ELEMENTLEVEL_TO_EQUIP")] EGEC_REQ_ELEMENTLEVEL_TO_EQUIP = 1506,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_ELEMENTLEVEL_TO_EQUIP")] EGEC_ACK_ELEMENTLEVEL_TO_EQUIP = 1507,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_WEAR_EQUIP")] EGEC_WEAR_EQUIP = 1508,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_TAKEOFF_EQUIP")] EGEC_TAKEOFF_EQUIP = 1509,
    /// <summary>
    ///                                
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_SET_FIGHT_HERO")] EGEC_REQ_SET_FIGHT_HERO = 1520,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_SWITCH_FIGHT_HERO")] EGEC_REQ_SWITCH_FIGHT_HERO = 1521,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_MINING_TITLE")] EGEC_REQ_MINING_TITLE = 1600,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_ACK_MINING_TITLE")] EGEC_ACK_MINING_TITLE = 1601,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_SEND_MAIL")] EGEC_REQ_SEND_MAIL = 1700,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_DRAW_MAIL")] EGEC_REQ_DRAW_MAIL = 1701,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGEC_REQ_DELETE_MAIL")] EGEC_REQ_DELETE_MAIL = 1702,
    /// <summary>
    ///clone
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_OBJECT_ENTRY")] EGMI_ACK_CLONE_OBJECT_ENTRY = 1800,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_OBJECT_LEAVE")] EGMI_ACK_CLONE_OBJECT_LEAVE = 1801,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_OBJECT_PROPERTY_ENTRY")] EGMI_ACK_CLONE_OBJECT_PROPERTY_ENTRY = 1802,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_OBJECT_RECORD_ENTRY")] EGMI_ACK_CLONE_OBJECT_RECORD_ENTRY = 1803,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_PROPERTY_INT")] EGMI_ACK_CLONE_PROPERTY_INT = 1810,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_PROPERTY_FLOAT")] EGMI_ACK_CLONE_PROPERTY_FLOAT = 1811,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_PROPERTY_STRING")] EGMI_ACK_CLONE_PROPERTY_STRING = 1812,
    /// <summary>
    ///EGMI_ACK_CLONE_PROPERTY_DOUBLE				= 1813;			//
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CLONE_PROPERTY_OBJECT")] EGMI_ACK_CLONE_PROPERTY_OBJECT = 1814,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQSWICHSERVER")] EGMI_REQSWICHSERVER = 1840,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACKSWICHSERVER")] EGMI_ACKSWICHSERVER = 1841,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CREATE_TEAM")] EGMI_REQ_CREATE_TEAM = 1860,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_CREATE_TEAM")] EGMI_ACK_CREATE_TEAM = 1861,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_JOIN_TEAM")] EGMI_REQ_JOIN_TEAM = 1862,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_JOIN_TEAM")] EGMI_ACK_JOIN_TEAM = 1863,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LEAVE_TEAM")] EGMI_REQ_LEAVE_TEAM = 1864,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LEAVE_TEAM")] EGMI_ACK_LEAVE_TEAM = 1865,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_INVITE_TEAM")] EGMI_REQ_INVITE_TEAM = 1866,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_OPRMEMBER_TEAM")] EGMI_REQ_OPRMEMBER_TEAM = 1867,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_OPRMEMBER_TEAM")] EGMI_ACK_OPRMEMBER_TEAM = 1868,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_TEAM_ENTER_ECTYPE")] EGMI_REQ_TEAM_ENTER_ECTYPE = 1869,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_TEAM_ENTER_ECTYPE")] EGMI_ACK_TEAM_ENTER_ECTYPE = 1870,
    /// <summary>
    //////////////////////MapModule/////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_MAP_GRID_INFO")] EGMI_REQ_MAP_GRID_INFO = 1900,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_MAP_GRID_INFO")] EGMI_ACK_MAP_GRID_INFO = 1901,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_BIG_MAP_INFO")] EGMI_REQ_BIG_MAP_INFO = 1902,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_BIG_MAP_INFO")] EGMI_ACK_BIG_MAP_INFO = 1903,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_HOLD_MAP_GRID")] EGMI_REQ_HOLD_MAP_GRID = 1910,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_HOLD_MAP_GRID")] EGMI_ACK_HOLD_MAP_GRID = 1911,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_LEAVE_MSG_MAP_GRID")] EGMI_REQ_LEAVE_MSG_MAP_GRID = 1912,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_LEAVE_MSG_MAP_GRID")] EGMI_ACK_LEAVE_MSG_MAP_GRID = 1913,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_GET_MAP_GRID_AWARD")] EGMI_REQ_GET_MAP_GRID_AWARD = 1914,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_GET_MAP_GRID_AWARD")] EGMI_ACK_GET_MAP_GRID_AWARD = 1915,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_MAP_GRID_HUNTING")] EGMI_REQ_MAP_GRID_HUNTING = 1916,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_MAP_GRID_HUNTING")] EGMI_ACK_MAP_GRID_HUNTING = 1917,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_MAP_GRID_KING_WAR")] EGMI_REQ_MAP_GRID_KING_WAR = 1918,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_ACK_MAP_GRID_KING_WAR")] EGMI_ACK_MAP_GRID_KING_WAR = 1919,
    /// <summary>
    //////////////////////GM MSG/////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_PROPERTY_INT")] EGMI_REQ_CMD_PROPERTY_INT = 10000,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_PROPERTY_STR")] EGMI_REQ_CMD_PROPERTY_STR = 10001,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_PROPERTY_OBJECT")] EGMI_REQ_CMD_PROPERTY_OBJECT = 10002,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_PROPERTY_FLOAT")] EGMI_REQ_CMD_PROPERTY_FLOAT = 10003,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_RECORD_INT")] EGMI_REQ_CMD_RECORD_INT = 10004,
    /// <summary>
    ///ַ
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_RECORD_STR")] EGMI_REQ_CMD_RECORD_STR = 10005,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_RECORD_OBJECT")] EGMI_REQ_CMD_RECORD_OBJECT = 10006,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_RECORD_FLOAT")] EGMI_REQ_CMD_RECORD_FLOAT = 10007,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_CMD_NORMAL")] EGMI_REQ_CMD_NORMAL = 10008,
    [pbr::OriginalName("EGMI_REQ_QUERY_SERVER_STATUS")] EGMI_REQ_QUERY_SERVER_STATUS = 10200,
    /// <summary>
    //////////////////////Base SLG MSG/////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_BUY_FORM_SHOP")] EGMI_REQ_BUY_FORM_SHOP = 20000,
    [pbr::OriginalName("EGMI_ACK_BUY_FORM_SHOP")] EGMI_ACK_BUY_FORM_SHOP = 20001,
    [pbr::OriginalName("EGMI_REQ_MOVE_BUILD_OBJECT")] EGMI_REQ_MOVE_BUILD_OBJECT = 20002,
    [pbr::OriginalName("EGMI_ACK_MOVE_BUILD_OBJECT")] EGMI_ACK_MOVE_BUILD_OBJECT = 20003,
    [pbr::OriginalName("EGMI_REQ_UP_BUILD_LVL")] EGMI_REQ_UP_BUILD_LVL = 20101,
    [pbr::OriginalName("EGMI_REQ_CREATE_ITEM")] EGMI_REQ_CREATE_ITEM = 20102,
    [pbr::OriginalName("EGMI_REQ_BUILD_OPERATE")] EGMI_REQ_BUILD_OPERATE = 20103,
    /// <summary>
    //////////////////////Base SHARE-TOOL MSG/////////////////////////////////////
    /// </summary>
    [pbr::OriginalName("EGMI_REQ_SEARCH_TO_SHARE")] EGMI_REQ_SEARCH_TO_SHARE = 30000,
    [pbr::OriginalName("EGMI_ACK_SEARCH_TO_SHARE")] EGMI_ACK_SEARCH_TO_SHARE = 30001,
    [pbr::OriginalName("EGMI_REQ_SHARE_TO_ATART")] EGMI_REQ_SHARE_TO_ATART = 30002,
    [pbr::OriginalName("EGMI_ACK_SHARE_TO_ATART")] EGMI_ACK_SHARE_TO_ATART = 30003,
  }

  /// <summary>
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  ///PropertyType
  /// </summary>
  public enum ESkillType {
    /// <summary>
    ///this kind of skill just can damage one object
    /// </summary>
    [pbr::OriginalName("EST_BRIEF_SINGLE")] EST_BRIEF_SINGLE = 0,
    /// <summary>
    ///this kind of skill can damage multiple objects
    /// </summary>
    [pbr::OriginalName("EST_BRIEF_GROUP")] EST_BRIEF_GROUP = 1,
    /// <summary>
    ///this kind of bullet just can damage one object
    /// </summary>
    [pbr::OriginalName("EST_BULLET_SINGLE")] EST_BULLET_SINGLE = 2,
    /// <summary>
    ///this kind of bullet can damage multiple objects via rebound
    /// </summary>
    [pbr::OriginalName("EST_BULLET_REBOUND")] EST_BULLET_REBOUND = 3,
    /// <summary>
    ///this kind of bullet can damage multiple objects when touch the target object(position)
    /// </summary>
    [pbr::OriginalName("EST_BULLET_BOMB")] EST_BULLET_BOMB = 4,
    /// <summary>
    ///???????
    /// </summary>
    [pbr::OriginalName("EST_TARGET_SINGLE")] EST_TARGET_SINGLE = 5,
    /// <summary>
    ///????????
    /// </summary>
    [pbr::OriginalName("EST_TARGET_GROUP")] EST_TARGET_GROUP = 6,
    /// <summary>
    ///??????(????????position)
    /// </summary>
    [pbr::OriginalName("EST_POSITION_GROUP")] EST_POSITION_GROUP = 7,
  }

  public enum EItemType {
    /// <summary>
    ///the equipment which can add props
    /// </summary>
    [pbr::OriginalName("EIT_EQUIP")] EIT_EQUIP = 0,
    /// <summary>
    ///the gem ca be embed to the equipment
    /// </summary>
    [pbr::OriginalName("EIT_GEM")] EIT_GEM = 1,
    /// <summary>
    ///expendable items for player, such as a medicine that cures
    /// </summary>
    [pbr::OriginalName("EIT_ITEM")] EIT_ITEM = 2,
    /// <summary>
    ///special items that can call a hero or others
    /// </summary>
    [pbr::OriginalName("EIT_CARD")] EIT_CARD = 3,
    /// <summary>
    ///special items can do what you want to do
    /// </summary>
    [pbr::OriginalName("EIT_TOKEN")] EIT_TOKEN = 4,
  }

  /// <summary>
  ///the sub items type of EIT_EQUIP
  /// </summary>
  public enum EGameEquipSubType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_WEAPON")] EQUIPTYPE_WEAPON = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_HELMET")] EQUIPTYPE_HELMET = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_ARMOR")] EQUIPTYPE_ARMOR = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_WRIST")] EQUIPTYPE_WRIST = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_PANT")] EQUIPTYPE_PANT = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EQUIPTYPE_BOOT")] EQUIPTYPE_BOOT = 5,
  }

  /// <summary>
  ///the sub items type of EIT_GEM
  /// </summary>
  public enum EGameGemSubType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_ATK")] EGGSTYPE_GEM_ATK = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_DEF")] EGGSTYPE_GEM_DEF = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_FIRE")] EGGSTYPE_GEM_FIRE = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_LIGHT")] EGGSTYPE_GEM_LIGHT = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_WIND")] EGGSTYPE_GEM_WIND = 5,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_ICE")] EGGSTYPE_GEM_ICE = 6,
    /// <summary>
    ///	
    /// </summary>
    [pbr::OriginalName("EGGSTYPE_GEM_POISON")] EGGSTYPE_GEM_POISON = 7,
  }

  /// <summary>
  ///the sub items type of EIT_ITEM
  /// </summary>
  public enum EGameItemSubType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_WATER")] EGIT_ITEM_WATER = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_DIAMOND")] EGIT_ITEM_DIAMOND = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_CURRENCY")] EGIT_ITEM_CURRENCY = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_EXP")] EGIT_ITEM_EXP = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_HP")] EGIT_ITEM_HP = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_MP")] EGIT_ITEM_MP = 5,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_SP")] EGIT_ITEM_SP = 6,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_PACK")] EGIT_ITEM_PACK = 7,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIT_ITEM_MEMORY_POS")] EGIT_ITEM_MEMORY_POS = 8,
  }

  /// <summary>
  ///the sub items type of EIT_CARD
  /// </summary>
  public enum EGameCardSubType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGCST_UNKNOW")] EGCST_UNKNOW = 0,
    /// <summary>
    ///	
    /// </summary>
    [pbr::OriginalName("EGCST_STRENGTH")] EGCST_STRENGTH = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGCST_AGILITY")] EGCST_AGILITY = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGCST_INTELLIGENCE")] EGCST_INTELLIGENCE = 3,
  }

  /// <summary>
  ///the sub items type of EIT_TOKEN
  /// </summary>
  public enum EGameTokenSubType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGTST_TOKEN_REBORN")] EGTST_TOKEN_REBORN = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGTST_TOKEN_POSITION")] EGTST_TOKEN_POSITION = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGTST_TOKEN_BOUNTY")] EGTST_TOKEN_BOUNTY = 2,
    /// <summary>
    ///a token that can join a activity
    /// </summary>
    [pbr::OriginalName("EGTST_TOKEN_ACTIVITY")] EGTST_TOKEN_ACTIVITY = 3,
    /// <summary>
    ///a token that can call a building or power
    /// </summary>
    [pbr::OriginalName("EGTST_TOKEN_BUILD")] EGTST_TOKEN_BUILD = 4,
  }

  /// <summary>
  /// </summary>
  public enum EGameItemExpiredType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIET_NONE")] EGIET_NONE = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIET_USE_TIMES")] EGIET_USE_TIMES = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EGIET_REAL_TIME")] EGIET_REAL_TIME = 2,
    [pbr::OriginalName("EGIET_END_INDEX")] EGIET_END_INDEX = 3,
  }

  public enum EDrawDropItemState {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("E_DRAW_STATE_NONE")] E_DRAW_STATE_NONE = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("E_DRAW_STATE_GAIN")] E_DRAW_STATE_GAIN = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("E_DRAW_STATE_RECV")] E_DRAW_STATE_RECV = 2,
  }

  /// <summary>
  ////////////////////////////////////////////////////////////////////////////////////////////////////
  /// </summary>
  public enum EGuildPowerType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("GUILD_POWER_TYPE_NORMAL")] GUILD_POWER_TYPE_NORMAL = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("GUILD_POWER_TYPE_VICE_PRESIDENT")] GUILD_POWER_TYPE_VICE_PRESIDENT = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("GUILD_POWER_TYPE_PRESIDENT")] GUILD_POWER_TYPE_PRESIDENT = 2,
  }

  /// <summary>
  /// </summary>
  public enum ETaskState {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_IN_PROCESS")] TASK_IN_PROCESS = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_DONE")] TASK_DONE = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_DRAW_AWARD")] TASK_DRAW_AWARD = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_FINISH")] TASK_FINISH = 3,
  }

  /// <summary>
  /// </summary>
  public enum ETaskType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_LEVEL_UPDATE_SOME_LEVEL")] TASK_LEVEL_UPDATE_SOME_LEVEL = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_PASS_ECTYPE")] TASK_PASS_ECTYPE = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_PASS_ECTYPE_COUNT")] TASK_PASS_ECTYPE_COUNT = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_PASS_SOME_TYPE_ECTYPE_COUNT")] TASK_PASS_SOME_TYPE_ECTYPE_COUNT = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_UPDATE_SKILL_COUNT")] TASK_UPDATE_SKILL_COUNT = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_CONSUME_MONEY")] TASK_CONSUME_MONEY = 5,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_CONSUME_DIAMOND")] TASK_CONSUME_DIAMOND = 6,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_ARENA_COUNT")] TASK_ARENA_COUNT = 7,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_KILL_MONSTER_COUNT")] TASK_KILL_MONSTER_COUNT = 8,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("TASK_KILL_SOME_MONSTER_COUNT")] TASK_KILL_SOME_MONSTER_COUNT = 9,
  }

  /// <summary>
  /// </summary>
  public enum EPVPType {
    [pbr::OriginalName("PVP_HOME")] PVP_HOME = 0,
    [pbr::OriginalName("PVP_INDIVIDUAL")] PVP_INDIVIDUAL = 1,
    [pbr::OriginalName("PVP_DOTA")] PVP_DOTA = 2,
    [pbr::OriginalName("PVP_SURVIVAL")] PVP_SURVIVAL = 3,
    [pbr::OriginalName("PVP_GUILD_WAR")] PVP_GUILD_WAR = 4,
    [pbr::OriginalName("PVP_GUILD_DUNGEON")] PVP_GUILD_DUNGEON = 5,
  }

  public enum EShopType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EST_UNKNOW")] EST_UNKNOW = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EST_BUILDING")] EST_BUILDING = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EST_GOLD")] EST_GOLD = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EST_ITEM")] EST_ITEM = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EST_EQUIP")] EST_EQUIP = 5,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EST_GEM")] EST_GEM = 6,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EST_CARD")] EST_CARD = 7,
  }

  public enum ERankType {
    [pbr::OriginalName("ERT_UNKNOW")] ERT_UNKNOW = 0,
    [pbr::OriginalName("ERT_PLAYER_LEVEL")] ERT_PLAYER_LEVEL = 1,
    [pbr::OriginalName("ERT_FIGHT_VALUE")] ERT_FIGHT_VALUE = 2,
    [pbr::OriginalName("ERT_PLAYER_MONEY")] ERT_PLAYER_MONEY = 3,
    [pbr::OriginalName("ERT_GUILD_LEVEL")] ERT_GUILD_LEVEL = 4,
    [pbr::OriginalName("ERT_GUILD_KINGSOURCE")] ERT_GUILD_KINGSOURCE = 5,
  }

  /// <summary>
  ///NPCTypenpc
  /// </summary>
  public enum ENPCType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ENPCTYPE_NORMAL")] ENPCTYPE_NORMAL = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ENPCTYPE_HERO")] ENPCTYPE_HERO = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ENPCTYPE_TURRET")] ENPCTYPE_TURRET = 2,
  }

  public enum ETARGETType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ETARGETTYPE_ENEMY")] ETARGETTYPE_ENEMY = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ETARGETTYPE_SELF")] ETARGETTYPE_SELF = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("ETARGETTYPE_FRIEND")] ETARGETTYPE_FRIEND = 2,
  }

  /// <summary>
  ///PropertyType
  /// </summary>
  public enum EPropertyType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EPT_UNKNOW")] EPT_UNKNOW = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EPT_STRENGTH")] EPT_STRENGTH = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EPT_AGILITY")] EPT_AGILITY = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EPT_INTELLIGENCE")] EPT_INTELLIGENCE = 3,
  }

  /// <summary>
  /// </summary>
  public enum EGameElementType {
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_FIRE")] EELEMENTTYPE_FIRE = 0,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_LIGHT")] EELEMENTTYPE_LIGHT = 1,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_WIND")] EELEMENTTYPE_WIND = 2,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_ICE")] EELEMENTTYPE_ICE = 3,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_POISON")] EELEMENTTYPE_POISON = 4,
    /// <summary>
    /// </summary>
    [pbr::OriginalName("EELEMENTTYPE_DARK")] EELEMENTTYPE_DARK = 5,
  }

  #endregion

}

#endregion Designer generated code
