CREATE TABLE IF NOT EXISTS Buff  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS ConsumeData  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS DescData  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS EffectData  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS Equip  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS GM  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS Guild  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS GuildConfig  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS GuildJob  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS IObject  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS InitProperty  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS Item  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS Language  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS Map  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS NPC  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS NoSqlServer  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS Player  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS Scene  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS Security  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS Server  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS Shop  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS Skill  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS SqlServer  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS Talent  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS Task  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
CREATE TABLE IF NOT EXISTS Team  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `Buff` ADD `DownSaveType` bigint(11) DEFAULT '0' COMMENT '下线是否保存'; 
ALTER TABLE `Buff` ADD `EffectClearOnDead` bigint(11) DEFAULT '0' COMMENT '死亡是否清除'; 
ALTER TABLE `Buff` ADD `EffectTimeInterval` double DEFAULT '0.0' COMMENT '每次间隔时间0.5f倍数'; 
ALTER TABLE `Buff` ADD `EffectTimeValue` bigint(11) DEFAULT '0' COMMENT '总共产生几次'; 
ALTER TABLE `Buff` ADD `EffectType` bigint(11) DEFAULT '0' COMMENT '影响属性类型(效果类型)  生命，法力(可组合,叠加)'; 
ALTER TABLE `Buff` ADD `EffectValueReferType` bigint(11) DEFAULT '0' COMMENT '影响值参考类型'; 
ALTER TABLE `Buff` ADD `EffectValueType` bigint(11) DEFAULT '0' COMMENT '影响值类型 百分比 绝对值--如果是控制属性开关，则只能是绝对值'; 
ALTER TABLE `Buff` ADD `ReverseReferType` bigint(11) DEFAULT '0' COMMENT '是否还原，不还原的在计算的时候不能保存在runTimeInfo,只能累计在最终值内'; 
ALTER TABLE `Buff` ADD `WashGroupID` bigint(11) DEFAULT '0' COMMENT '每次间隔时间0.5f倍数'; 
ALTER TABLE `ConsumeData` ADD `Diamond` bigint(11) DEFAULT '0' COMMENT '钻石'; 
ALTER TABLE `ConsumeData` ADD `EXP` bigint(11) DEFAULT '0' COMMENT '经验获得,如果是怪物，则是掉落经验'; 
ALTER TABLE `ConsumeData` ADD `Gold` bigint(11) DEFAULT '0' COMMENT '玩家游戏金币'; 
ALTER TABLE `ConsumeData` ADD `HP` bigint(11) DEFAULT '0' COMMENT '生命值'; 
ALTER TABLE `ConsumeData` ADD `MP` bigint(11) DEFAULT '0' COMMENT '法力值'; 
ALTER TABLE `ConsumeData` ADD `SP` bigint(11) DEFAULT '0' COMMENT '体力'; 
ALTER TABLE `ConsumeData` ADD `VIPEXP` bigint(11) DEFAULT '0' COMMENT 'VIP经验'; 
ALTER TABLE `Guild` ADD `Guild_AD` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT '工会公告'; 
ALTER TABLE `Guild` ADD `Guild_ContinueDay` bigint(11) DEFAULT '0' COMMENT '工会霸占排行榜天数'; 
ALTER TABLE `Guild` ADD `Guild_CreateTime` bigint(11) DEFAULT '0' COMMENT '公会创建时间'; 
ALTER TABLE `Guild` ADD `Guild_Desc` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT '工会描述'; 
ALTER TABLE `Guild` ADD `Guild_EctypID` bigint(11) DEFAULT '0' COMMENT '工会副本ID'; 
ALTER TABLE `Guild` ADD `Guild_EctypServer` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '工会副本所在的服'; 
ALTER TABLE `Guild` ADD `Guild_Exp` bigint(11) DEFAULT '0' COMMENT '公会经验'; 
ALTER TABLE `Guild` ADD `Guild_Gold` bigint(11) DEFAULT '0' COMMENT '工会财富'; 
ALTER TABLE `Guild` ADD `Guild_Honor` bigint(11) DEFAULT '0' COMMENT '公会荣誉'; 
ALTER TABLE `Guild` ADD `Guild_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '工会ID'; 
ALTER TABLE `Guild` ADD `Guild_Icon` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT '公会头像'; 
ALTER TABLE `Guild` ADD `Guild_KingWarResource` bigint(11) DEFAULT '0' COMMENT '获得的战役资源'; 
ALTER TABLE `Guild` ADD `Guild_Level` bigint(11) DEFAULT '0' COMMENT '工会等级'; 
ALTER TABLE `Guild` ADD `Guild_MemeberCount` bigint(11) DEFAULT '0' COMMENT '成员数量(增加个字段，不然遍历Record太麻烦)'; 
ALTER TABLE `Guild` ADD `Guild_MemeberMaxCount` bigint(11) DEFAULT '0' COMMENT '成员最大数量'; 
ALTER TABLE `Guild` ADD `Guild_Name` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT '工会名'; 
ALTER TABLE `Guild` ADD `Guild_PresidentID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '会长ID'; 
ALTER TABLE `Guild` ADD `Guild_PresidentName` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT '会长名'; 
ALTER TABLE `Guild` ADD `Guild_Rank` bigint(11) DEFAULT '0' COMMENT '公会排名'; 
ALTER TABLE `Guild` ADD `Guild_Status` bigint(11) DEFAULT '0' COMMENT '公会状态，正常状态，申请解散状态'; 
CREATE TABLE IF NOT EXISTS GuildGuild_AppyList  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `GuildGuild_AppyList` ADD `GuildID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `GuildGuild_AppyList` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_AppyList` ADD `GUID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `GuildGuild_AppyList` ADD `Level` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_AppyList` ADD `Name` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `GuildGuild_AppyList` ADD `VIP` bigint(11) DEFAULT '0' COMMENT ''; 
CREATE TABLE IF NOT EXISTS GuildGuild_Building  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `GuildGuild_Building` ADD `GuildID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `GuildGuild_Building` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_Building` ADD `GUID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `GuildGuild_Building` ADD `Level` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_Building` ADD `Name` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
CREATE TABLE IF NOT EXISTS GuildGuild_MemberList  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `GuildGuild_MemberList` ADD `GuildID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `GuildGuild_MemberList` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_MemberList` ADD `AllContribution` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_MemberList` ADD `Contribution` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_MemberList` ADD `Donation` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_MemberList` ADD `GUID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `GuildGuild_MemberList` ADD `GameID` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_MemberList` ADD `Job` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_MemberList` ADD `JoinTime` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_MemberList` ADD `LastTime` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `GuildGuild_MemberList` ADD `Level` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_MemberList` ADD `Name` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `GuildGuild_MemberList` ADD `Online` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_MemberList` ADD `Power` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_MemberList` ADD `Receive` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_MemberList` ADD `Title` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_MemberList` ADD `VIP` bigint(11) DEFAULT '0' COMMENT ''; 
CREATE TABLE IF NOT EXISTS GuildGuild_WarList  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `GuildGuild_WarList` ADD `GuildID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `GuildGuild_WarList` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `GuildGuild_WarList` ADD `GUID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `GuildGuild_WarList` ADD `Level` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `IObject` ADD `ClassName` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `IObject` ADD `ConfigID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `Map` ADD `MaxCount` bigint(11) DEFAULT '0' COMMENT '最大入驻公会'; 
CREATE TABLE IF NOT EXISTS MapStation  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `MapStation` ADD `MapID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `MapStation` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `MapStation` ADD `CurMemberCount` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `MapStation` ADD `GUID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `MapStation` ADD `GuildID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `MapStation` ADD `GuildName` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `MapStation` ADD `Level` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `MapStation` ADD `Slogan` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `MapStation` ADD `State` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `MapStation` ADD `Title` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `MapStation` ADD `WinCount` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `NPC` ADD `AIOwnerID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'AI'; 
ALTER TABLE `NPC` ADD `Camp` bigint(11) DEFAULT '0' COMMENT '阵营'; 
ALTER TABLE `NPC` ADD `Diamond` bigint(11) DEFAULT '0' COMMENT '钻石'; 
ALTER TABLE `NPC` ADD `EXP` bigint(11) DEFAULT '0' COMMENT '经验获得,如果是怪物，则是掉落经验'; 
ALTER TABLE `NPC` ADD `Gold` bigint(11) DEFAULT '0' COMMENT '玩家游戏金币'; 
ALTER TABLE `NPC` ADD `HP` bigint(11) DEFAULT '0' COMMENT '生命值'; 
ALTER TABLE `NPC` ADD `Level` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `NPC` ADD `MP` bigint(11) DEFAULT '0' COMMENT '法力值'; 
ALTER TABLE `NPC` ADD `MasterID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '召唤者，主人'; 
ALTER TABLE `NPC` ADD `SP` bigint(11) DEFAULT '0' COMMENT '体力'; 
ALTER TABLE `NPC` ADD `VIPEXP` bigint(11) DEFAULT '0' COMMENT 'VIP经验'; 
CREATE TABLE IF NOT EXISTS NPCCooldown  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `NPCCooldown` ADD `NPCID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `NPCCooldown` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `NPCCooldown` ADD `SkillID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `NPCCooldown` ADD `Time` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `Player` ADD `ATK_PVP` bigint(11) DEFAULT '0' COMMENT 'PVP攻击力'; 
ALTER TABLE `Player` ADD `Account` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT '玩家的帐号'; 
ALTER TABLE `Player` ADD `Camp` bigint(11) DEFAULT '0' COMMENT '阵营'; 
ALTER TABLE `Player` ADD `ConnectKey` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT '玩家连接服务器的KEY'; 
ALTER TABLE `Player` ADD `Cup` bigint(11) DEFAULT '0' COMMENT 'Cup'; 
ALTER TABLE `Player` ADD `DEF_PVP` bigint(11) DEFAULT '0' COMMENT 'PVP防御力'; 
ALTER TABLE `Player` ADD `Diamond` bigint(11) DEFAULT '0' COMMENT '钻石'; 
ALTER TABLE `Player` ADD `EXP` bigint(11) DEFAULT '0' COMMENT '经验获得,如果是怪物，则是掉落经验'; 
ALTER TABLE `Player` ADD `FightHeroCnfID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT 'FightHeroCnfID'; 
ALTER TABLE `Player` ADD `FightHeroID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'FightHeroID'; 
ALTER TABLE `Player` ADD `FightingStar` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `Player` ADD `FirstTarget` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '首要目标'; 
ALTER TABLE `Player` ADD `GMLevel` bigint(11) DEFAULT '0' COMMENT 'GM等级'; 
ALTER TABLE `Player` ADD `Gold` bigint(11) DEFAULT '0' COMMENT '玩家游戏金币'; 
ALTER TABLE `Player` ADD `GuildID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '公会ID'; 
ALTER TABLE `Player` ADD `HP` bigint(11) DEFAULT '0' COMMENT '生命值'; 
ALTER TABLE `Player` ADD `Head` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT 'headicon--guild'; 
ALTER TABLE `Player` ADD `HeroCnfID1` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT 'Hero1'; 
ALTER TABLE `Player` ADD `HeroCnfID2` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT 'Hero2'; 
ALTER TABLE `Player` ADD `HeroCnfID3` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT 'Hero3'; 
ALTER TABLE `Player` ADD `HeroID1` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'Hero1'; 
ALTER TABLE `Player` ADD `HeroID2` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'Hero2'; 
ALTER TABLE `Player` ADD `HeroID3` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'Hero3'; 
ALTER TABLE `Player` ADD `HeroPos1` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'FightHeroHP1'; 
ALTER TABLE `Player` ADD `HeroPos2` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'FightHeroHP2'; 
ALTER TABLE `Player` ADD `HeroPos3` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT 'FightHeroHP3'; 
ALTER TABLE `Player` ADD `HeroStar1` bigint(11) DEFAULT '0' COMMENT 'Hero1'; 
ALTER TABLE `Player` ADD `HeroStar2` bigint(11) DEFAULT '0' COMMENT 'Hero2'; 
ALTER TABLE `Player` ADD `HeroStar3` bigint(11) DEFAULT '0' COMMENT 'Hero3'; 
ALTER TABLE `Player` ADD `HomeSceneID` bigint(11) DEFAULT '0' COMMENT '玩家下线的时候需要保存上次在线的场景'; 
ALTER TABLE `Player` ADD `Item1` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT 'Skill4'; 
ALTER TABLE `Player` ADD `Item1Count` bigint(11) DEFAULT '0' COMMENT 'Item1Count'; 
ALTER TABLE `Player` ADD `Item2` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT 'Skill5'; 
ALTER TABLE `Player` ADD `Item2Count` bigint(11) DEFAULT '0' COMMENT 'Item2Count'; 
ALTER TABLE `Player` ADD `Item3` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT 'Skill5'; 
ALTER TABLE `Player` ADD `Item3Count` bigint(11) DEFAULT '0' COMMENT 'Item3Count'; 
ALTER TABLE `Player` ADD `Job` bigint(11) DEFAULT '0' COMMENT '职业'; 
ALTER TABLE `Player` ADD `LastOfflineTime` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '上次下线时间'; 
ALTER TABLE `Player` ADD `Level` bigint(11) DEFAULT '0' COMMENT '等级'; 
ALTER TABLE `Player` ADD `MAXEXP` bigint(11) DEFAULT '0' COMMENT '升级需要的经验'; 
ALTER TABLE `Player` ADD `MP` bigint(11) DEFAULT '0' COMMENT '法力值'; 
ALTER TABLE `Player` ADD `Name` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT '角色名'; 
ALTER TABLE `Player` ADD `OnlineCount` bigint(11) DEFAULT '0' COMMENT '上线次数'; 
ALTER TABLE `Player` ADD `OnlineTime` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '本次上线时间'; 
ALTER TABLE `Player` ADD `PrefabPath` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT '预设路径'; 
ALTER TABLE `Player` ADD `RELIVE_SOUL` bigint(11) DEFAULT '0' COMMENT '转生次数'; 
ALTER TABLE `Player` ADD `Race` bigint(11) DEFAULT '0' COMMENT '种族'; 
ALTER TABLE `Player` ADD `SP` bigint(11) DEFAULT '0' COMMENT '体力'; 
ALTER TABLE `Player` ADD `Sex` bigint(11) DEFAULT '0' COMMENT '性别'; 
ALTER TABLE `Player` ADD `ShowName` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT '显示的名字'; 
ALTER TABLE `Player` ADD `Skill1` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT 'Skill1'; 
ALTER TABLE `Player` ADD `Skill2` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT 'Skill2'; 
ALTER TABLE `Player` ADD `Skill3` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT 'Skill3'; 
ALTER TABLE `Player` ADD `TeamID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '所在队伍ID'; 
ALTER TABLE `Player` ADD `TotalLineTime` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '今日在线时长{截至至本次上线时间}'; 
ALTER TABLE `Player` ADD `TotalTime` bigint(11) DEFAULT '0' COMMENT '在线时间'; 
ALTER TABLE `Player` ADD `VIPEXP` bigint(11) DEFAULT '0' COMMENT 'VIP经验'; 
ALTER TABLE `Player` ADD `VIPLevel` bigint(11) DEFAULT '0' COMMENT '经验获得,如果是怪物，则是掉落经验'; 
CREATE TABLE IF NOT EXISTS PlayerBagEquipList  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `PlayerBagEquipList` ADD `PlayerID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `ConfigID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `Date` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `ElementLevel1_FIRE` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `ElementLevel2_LIGHT` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `ElementLevel3_Wind` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `ElementLevel4_ICE` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `ElementLevel5_POISON` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `ExpiredType` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `GUID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `InlayStone1` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `InlayStone10` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `InlayStone2` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `InlayStone3` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `InlayStone4` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `InlayStone5` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `InlayStone6` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `InlayStone7` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `InlayStone8` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `InlayStone9` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `IntensifyLevel` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `RandPropertyID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `SlotCount` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBagEquipList` ADD `WearGUID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
CREATE TABLE IF NOT EXISTS PlayerBagItemList  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `PlayerBagItemList` ADD `PlayerID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagItemList` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBagItemList` ADD `Bound` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBagItemList` ADD `ConfigID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBagItemList` ADD `Date` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBagItemList` ADD `ExpiredType` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBagItemList` ADD `ItemCount` bigint(11) DEFAULT '0' COMMENT ''; 
CREATE TABLE IF NOT EXISTS PlayerBuildingList  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `PlayerBuildingList` ADD `PlayerID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBuildingList` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBuildingList` ADD `BuildingCnfID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBuildingList` ADD `BuildingGUID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBuildingList` ADD `Pos` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBuildingList` ADD `State` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBuildingList` ADD `StateEndTime` bigint(11) DEFAULT '0' COMMENT ''; 
CREATE TABLE IF NOT EXISTS PlayerBuildingListProduce  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `PlayerBuildingListProduce` ADD `PlayerID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBuildingListProduce` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBuildingListProduce` ADD `BuildingCnfID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBuildingListProduce` ADD `BuildingGUID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBuildingListProduce` ADD `Pos` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerBuildingListProduce` ADD `State` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerBuildingListProduce` ADD `StateEndTime` bigint(11) DEFAULT '0' COMMENT ''; 
CREATE TABLE IF NOT EXISTS PlayerCooldown  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `PlayerCooldown` ADD `PlayerID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerCooldown` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerCooldown` ADD `SkillID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerCooldown` ADD `Time` bigint(11) DEFAULT '0' COMMENT ''; 
CREATE TABLE IF NOT EXISTS PlayerGuild_AppyList  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `PlayerGuild_AppyList` ADD `PlayerID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerGuild_AppyList` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_AppyList` ADD `GUID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerGuild_AppyList` ADD `Level` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_AppyList` ADD `Name` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerGuild_AppyList` ADD `VIP` bigint(11) DEFAULT '0' COMMENT ''; 
CREATE TABLE IF NOT EXISTS PlayerGuild_Building  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `PlayerGuild_Building` ADD `PlayerID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerGuild_Building` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_Building` ADD `GUID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerGuild_Building` ADD `Level` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_Building` ADD `Name` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
CREATE TABLE IF NOT EXISTS PlayerGuild_MemberList  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `PlayerGuild_MemberList` ADD `PlayerID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerGuild_MemberList` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_MemberList` ADD `AllContribution` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_MemberList` ADD `Contribution` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_MemberList` ADD `Donation` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_MemberList` ADD `GUID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerGuild_MemberList` ADD `GameID` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_MemberList` ADD `Job` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_MemberList` ADD `JoinTime` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_MemberList` ADD `LastTime` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerGuild_MemberList` ADD `Level` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_MemberList` ADD `Name` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerGuild_MemberList` ADD `Online` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_MemberList` ADD `Power` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_MemberList` ADD `Receive` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_MemberList` ADD `Title` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_MemberList` ADD `VIP` bigint(11) DEFAULT '0' COMMENT ''; 
CREATE TABLE IF NOT EXISTS PlayerGuild_WarList  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `PlayerGuild_WarList` ADD `PlayerID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerGuild_WarList` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerGuild_WarList` ADD `GUID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerGuild_WarList` ADD `Level` bigint(11) DEFAULT '0' COMMENT ''; 
CREATE TABLE IF NOT EXISTS PlayerHeroValue  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `PlayerHeroValue` ADD `PlayerID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `ATK_DARK` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `ATK_FIRE` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `ATK_ICE` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `ATK_LIGHT` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `ATK_POISON` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `ATK_SPEED` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `ATK_VALUE` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `ATK_WIND` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `BUFF_GATE` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `CRITICAL` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `DEF_DARK` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `DEF_FIRE` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `DEF_ICE` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `DEF_LIGHT` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `DEF_POISON` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `DEF_VALUE` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `DEF_WIND` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `DIZZY_GATE` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `HPREGEN` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `MAGIC_GATE` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `MAXHP` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `MAXMP` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `MAXSP` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `MOVE_GATE` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `MOVE_SPEED` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `MPREGEN` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `PHYSICAL_GATE` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `REFLECTDAMAGE` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `SKILL_GATE` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `SPREGEN` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerHeroValue` ADD `SUCKBLOOD` bigint(11) DEFAULT '0' COMMENT ''; 
CREATE TABLE IF NOT EXISTS PlayerPlayerHero  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `PlayerPlayerHero` ADD `PlayerID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerPlayerHero` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerPlayerHero` ADD `Activated` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerPlayerHero` ADD `ConfigID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerPlayerHero` ADD `Dark_Talent` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerPlayerHero` ADD `Exp` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerPlayerHero` ADD `Fire_Talent` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerPlayerHero` ADD `GUID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerPlayerHero` ADD `Ice_Talent` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerPlayerHero` ADD `Level` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerPlayerHero` ADD `Light_Talent` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerPlayerHero` ADD `Poison_Talent` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerPlayerHero` ADD `Star` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerPlayerHero` ADD `Wind_Talent` bigint(11) DEFAULT '0' COMMENT ''; 
CREATE TABLE IF NOT EXISTS PlayerTaskList  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `PlayerTaskList` ADD `PlayerID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerTaskList` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerTaskList` ADD `Process` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerTaskList` ADD `TaskID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerTaskList` ADD `TaskStatus` bigint(11) DEFAULT '0' COMMENT ''; 
CREATE TABLE IF NOT EXISTS PlayerTaskMonsterList  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `PlayerTaskMonsterList` ADD `PlayerID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerTaskMonsterList` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerTaskMonsterList` ADD `CurrentKillCount` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerTaskMonsterList` ADD `MonsterID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerTaskMonsterList` ADD `RequireKillCount` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerTaskMonsterList` ADD `TaskID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
CREATE TABLE IF NOT EXISTS PlayerWarList  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `PlayerWarList` ADD `PlayerID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `AttackerCup` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `AttackerHeroList` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `AttackerHeroStarList` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `AttackerID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `AttackerLevel` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `AttackerName` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `BeAttackerCup` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `BeAttackerHeroList` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `BeAttackerHeroStarList` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `BeAttackerID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `BeAttackerLevel` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `BeAttackerName` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `CostTime` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `Diamond` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `EventTime` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `Gold` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `ItemList` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `WarID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `WarStar` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `PlayerWarList` ADD `Winner` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `Shop` ADD `Count` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `Shop` ADD `Diamond` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `Shop` ADD `Gold` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `Shop` ADD `ItemID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `Shop` ADD `Level` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `Shop` ADD `Steel` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `Shop` ADD `Stone` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `Shop` ADD `Type` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `Team` ADD `Captain` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '队长ID'; 
ALTER TABLE `Team` ADD `PresidentName` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT '会长名'; 
CREATE TABLE IF NOT EXISTS TeamApplyList  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `TeamApplyList` ADD `TeamID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `TeamApplyList` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `TeamApplyList` ADD `Donation` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `TeamApplyList` ADD `GUID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `TeamApplyList` ADD `Job` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `TeamApplyList` ADD `Level` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `TeamApplyList` ADD `Name` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `TeamApplyList` ADD `Power` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `TeamApplyList` ADD `VIP` bigint(11) DEFAULT '0' COMMENT ''; 
CREATE TABLE IF NOT EXISTS TeamMemberList  ( `ID` varchar(128) NOT NULL, PRIMARY KEY (`ID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8; 
ALTER TABLE `TeamMemberList` ADD `TeamID` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `TeamMemberList` ADD `Row` INT DEFAULT '0' COMMENT ''; 
ALTER TABLE `TeamMemberList` ADD `Donation` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `TeamMemberList` ADD `GUID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT ''; 
ALTER TABLE `TeamMemberList` ADD `GameID` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `TeamMemberList` ADD `Job` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `TeamMemberList` ADD `Level` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `TeamMemberList` ADD `Name` text COLLATE utf8mb4_unicode_ci  DEFAULT '' COMMENT ''; 
ALTER TABLE `TeamMemberList` ADD `Online` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `TeamMemberList` ADD `Receive` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `TeamMemberList` ADD `Title` bigint(11) DEFAULT '0' COMMENT ''; 
ALTER TABLE `TeamMemberList` ADD `VIP` bigint(11) DEFAULT '0' COMMENT ''; 
